# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\JustFin\dialog_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_log(object):
    def setupUi(self, Dialog_log):
        Dialog_log.setObjectName("Dialog_log")
        Dialog_log.resize(450, 400)
        Dialog_log.setMinimumSize(QtCore.QSize(450, 400))
        Dialog_log.setMaximumSize(QtCore.QSize(500, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\JustFin\\icon/free-icon-user-507637.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_log.setWindowIcon(icon)
        Dialog_log.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog_log)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(80, -1, 80, -1)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.last_name = QtWidgets.QLineEdit(Dialog_log)
        self.last_name.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.last_name.setFont(font)
        self.last_name.setStyleSheet(" QLineEdit {\n"
"     border: 2px solid rgb(255, 255, 255);\n"
"     border-radius: 10px;\n"
"     padding: 0 8px;\n"
"     background: rgb(232, 232, 232);\n"
"     selection-background-color: rgb(91, 91, 91);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
" }")
        self.last_name.setInputMask("")
        self.last_name.setMaxLength(32767)
        self.last_name.setAlignment(QtCore.Qt.AlignCenter)
        self.last_name.setObjectName("last_name")
        self.verticalLayout.addWidget(self.last_name)
        self.first_name = QtWidgets.QLineEdit(Dialog_log)
        self.first_name.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.first_name.setFont(font)
        self.first_name.setStyleSheet(" QLineEdit {\n"
"     border: 2px solid rgb(255, 255, 255);\n"
"     border-radius: 10px;\n"
"     padding: 0 8px;\n"
"     background: rgb(232, 232, 232);\n"
"     selection-background-color: rgb(91, 91, 91);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
" }")
        self.first_name.setMaxLength(20)
        self.first_name.setAlignment(QtCore.Qt.AlignCenter)
        self.first_name.setObjectName("first_name")
        self.verticalLayout.addWidget(self.first_name)
        self.create = QtWidgets.QPushButton(Dialog_log)
        self.create.setMinimumSize(QtCore.QSize(84, 30))
        self.create.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.create.setFont(font)
        self.create.setStyleSheet(" QPushButton {\n"
"     color: rgb(232, 232, 232);\n"
"     border: 2px solid #8f8f91;\n"
"     border-radius: 10px;\n"
"     background-color: rgb(49, 49, 49);\n"
"     min-width: 80px;\n"
" }\n"
"QPushButton:hover{\n"
"    color: rgb(49, 49, 49);\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
" QPushButton:pressed {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"     background-color: rgb(91, 91, 91);\n"
" }\n"
"\n"
" QPushButton:flat {\n"
"     border: none; /* для плоской кнопки границы нет */\n"
" }\n"
"")
        self.create.setObjectName("create")
        self.verticalLayout.addWidget(self.create)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_log)
        QtCore.QMetaObject.connectSlotsByName(Dialog_log)
        Dialog_log.setTabOrder(self.create, self.last_name)
        Dialog_log.setTabOrder(self.last_name, self.first_name)

    def retranslateUi(self, Dialog_log):
        _translate = QtCore.QCoreApplication.translate
        Dialog_log.setWindowTitle(_translate("Dialog_log", "Регистрация"))
        self.last_name.setPlaceholderText(_translate("Dialog_log", "Фамилия"))
        self.first_name.setPlaceholderText(_translate("Dialog_log", "Имя"))
        self.create.setText(_translate("Dialog_log", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_log = QtWidgets.QDialog()
    ui = Ui_Dialog_log()
    ui.setupUi(Dialog_log)
    Dialog_log.show()
    sys.exit(app.exec_())
